AC-130 Adding a new setting to control the time we wait for vm snapshot delete.
ippathways/cloudstack pull request #67
Opened 2023-02-14 21:16 UTC by nlgordon

2023-02-14 22:21 UTC, Slair1 requested changes

2023-02-14 22:21 UTC, Slair1 commented on engine/storage/snapshot/src/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
> +            "In second, timeout for delete of vm snapshot", false, ConfigKey.Scope.Global, null);
Small type "In seconds,"

2023-02-14 22:51 UTC, nlgordon commented on engine/storage/snapshot/src/org/apache/cloudstack/storage/vmsnapshot/DefaultVMSnapshotStrategy.java
> +            "In second, timeout for delete of vm snapshot", false, ConfigKey.Scope.Global, null);
Fixed

2023-04-14 13:52 UTC, Slair1 approved these changes

2023-04-14 13:53 UTC, merged