AC-83 Prompt to delete attached drives when deleting a VM
ippathways/cloudstack pull request #79
Opened 2023-07-07 02:24 UTC by bharkarampudi

### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

### How Has This Been Tested?

2023-08-01 00:32 UTC, Slair1 commented
Let's update the labels a little:
"Volumes to be deleted" = "Delete data volumes"
"Volume ID's" = "Data volumes"

@ggoodrich-ipp we need QA to test this

2023-08-07 21:01 UTC, bharkarampudi commented
@Slair1 ,
Currently this feature aims at to allow VM entity owners to delete any attached columns, either through the API or UI when a VM is being destroyed. If you want to delete the volumes for VMs launched in other profiles other than Root Domain we need to login using  those Account credentials  where vm is created and can delete it.

can you please confirm  whether or not Admin should be able to use this for another account/ when Admin try to login and wanted to destroy the vm created with  Domain and Account other than Root, he can see the volumes and can delete it?

2023-08-11 14:00 UTC, Slair1 commented
> @Slair1 , Currently this feature aims at to allow VM entity owners to delete any attached columns, either through the API or UI when a VM is being destroyed. If you want to delete the volumes for VMs launched in other profiles other than Root Domain we need to login using those Account credentials where vm is created and can delete it.
> 
> can you please confirm whether or not Admin should be able to use this for another account/ when Admin try to login and wanted to destroy the vm created with Domain and Account other than Root, he can see the volumes and can delete it?

@bharkarampudi This should also work the same for a Root Admin or Domain Admin.  They should be able to delete VMs and associated Volumes for sub-accounts.  Did i understand your question correctly?

2023-08-23 15:21 UTC, Slair1 commented
@ggoodrich-ipp Has QA looked at this?
@nlgordon Have you reviewed?
@bharkarampudi i think this needs re-baselined to 4.11-ipp because of our last set of commits

2023-08-23 19:44 UTC, bharkarampudi commented
> @ggoodrich-ipp Has QA looked at this? @nlgordon Have you reviewed? @bharkarampudi i think this needs re-baselined to 4.11-ipp because of our last set of commits
Rebased with 4.11-ipp

2023-08-29 16:09 UTC, bharkarampudi commented
> @ggoodrich-ipp Has QA looked at this? @nlgordon Have you reviewed? @bharkarampudi i think this needs re-baselined to 4.11-ipp because of our last set of commits

@Slair1  QA has tested this.

2023-08-29 18:13 UTC, nlgordon requested changes

2023-08-29 18:13 UTC, nlgordon commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +        List<VolumeVO> volumes = getVolumesFromIds(cmd);
The UI is limiting to only data disks. We should also apply that logic in the API to match.

2023-08-29 18:13 UTC, nlgordon commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +        stopVirtualMachine(vmId, VmDestroyForcestop.value());
Do we need to stop and detach the volumes if we destroy it a few lines later? Or is it a problem where the objects need to be re-queried to be in the correct state?

2023-08-29 18:13 UTC, nlgordon commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +                s_logger.error("DestroyVM remove volume - failed to delete volume " + volume.getInstanceId() + " from instance " + volume.getId());
Does this need to be an exception since it didn't perform what the user was expecting? If it fails they won't get any feedback.

2023-08-29 18:13 UTC, nlgordon commented on server/src/com/cloud/vm/UserVmManagerImpl.java
In the future, we want to avoid doing reformatting on existing files. This will make merging our changes forward and finding the actual change more difficult.

2023-10-06 13:54 UTC, bharkarampudi commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +        stopVirtualMachine(vmId, VmDestroyForcestop.value());
@nlgordon  Yeah I see your point, we dont have to stop the VM to detach.  But to make the detach operations safer or not to fail, I think it is better to stop the VM and then continue the flow.

2023-10-06 13:58 UTC, bharkarampudi commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +                s_logger.error("DestroyVM remove volume - failed to delete volume " + volume.getInstanceId() + " from instance " + volume.getId());
If we throw the exception here, the VM will be in unexpected state like VM will be in stopped state and some other data volumes might have already deleted which cannot be reverted. I think it is better to continue and destroy the VM, if there is a failure happened for any data disk, atmost user may have to delete the volume later. 
This message cannot be given back to user, so logging it for tracking purpose.

2023-10-09 13:07 UTC, bharkarampudi commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +        List<VolumeVO> volumes = getVolumesFromIds(cmd);
Made changes, if disk type is other than Datadisk exception is thrown

2023-10-31 16:13 UTC, nlgordon commented on server/src/com/cloud/vm/UserVmManagerImpl.java
> +                s_logger.error("DestroyVM remove volume - failed to delete volume " + volume.getInstanceId() + " from instance " + volume.getId());
Hmmm, that is unfortunate, but if that is how it works it will have to do.

2023-10-31 16:25 UTC, nlgordon approved these changes

2023-11-24 01:19 UTC, merged