Ac 149
ippathways/cloudstack pull request #86
Opened 2023-10-23 17:46 UTC by bharkarampudi

### Description

This PR...

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

### How Has This Been Tested?

2023-11-21 20:21 UTC, nlgordon requested changes

2023-11-21 20:21 UTC, nlgordon commented on engine/schema/src/com/cloud/upgrade/dao/Upgrade41130to41131.java
> +            stmt = conn.prepareStatement("alter table network_acl_item_cidrs add column is_source_cidr tinyint(1) DEFAULT NULL");
These need to go in a new version. 4.11.3.2 Otherwise they won't get applied since the mgmt server is already 4.11.3.1.

2023-11-21 20:21 UTC, nlgordon commented on core/src/com/cloud/agent/resource/virtualnetwork/model/AclRule.java
> +    private Long ruleId;
Is there a reason this was added? It doesn't seem to be referenced anywhere.

2023-11-21 20:21 UTC, nlgordon commented on engine/schema/src/com/cloud/network/vpc/dao/NetworkACLItemCidrsDaoImpl.java
> +        cidrsSearch.and("isSourceCidr", cidrsSearch.entity().getIsSourceCidr(), SearchCriteria.Op.EQ);
I don't think this will work like you expect. The db column will have null as a default as you have specified in the migration. But in java you are mapping null to true. So this probably won't return any existing records as source cidrs even though they are in the database because the query will be looking for true. I think instead you want to make the db column default to true, or update all existing records to be true. Then get rid of the null -> true mapping in java.

2023-11-21 20:21 UTC, nlgordon commented on core/src/com/cloud/agent/resource/virtualnetwork/model/AclRule.java
> +    private Long ruleId;
I see where this is now being used in the router python code. I'm still wondering why we are adding this since the old system in theory worked without it?

2023-12-05 14:39 UTC, bharkarampudi commented
closing this and will open this PR in private branch.

2023-12-05 14:39 UTC, closed without merging